# Site settings
title: HOAR
email: theodore.barnhart@colorado.edu
url: https://HOARorg.github.io
description: "HOAR (Hydrologists of Alpine Regions) is a community of snow and mountain hydrology researchers, professionals, and enthusiasts."
skills: "Snow! - Community Building - Mountain Hydrology"
meta_author: Barnhart Theo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 02d9ff #80B3FF
  primary-rgb: "128,179,255" #"128,179,255"
  secondary: FD6E8A #FD6E8A
  secondary-dark: A2122F #A2122F

# Footer settings
footer:
  copyright: HOAR
  location: Boulder, CO
  #social: Around the Web
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/HOARorg

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
